[[sites]]
  id = "comfi.es"
  url = "https://comfi.es/"

[[sites]]
  id = "dystopia.club"
  url = "https://dystopia.club/"

[[sites]]
  id = "zvava.org"
  url = "https://zvava.org"
  css = "https://zvava.org/src/webcircle.css"

[[sites]]
  id = "lllil.li"
  url = "https://lllil.li"
