[[sites]]
  id = "comfi.es"
  url = "https://comfi.es/"
  css = "https://comfi.es/src/webcircle.css"

[[sites]]
  id = "dystopia.club"
  url = "https://dystopia.club/"
  css = "https://dystopia.club/circle.css"

[[sites]]
  id = "zvava.org"
  url = "https://zvava.org/"
  css = "https://zvava.org/src/webcircle.css"

[[sites]]
  id = "lllil.li"
  url = "https://lllil.li/"
  css = "https://lllil.li/static/css/webcircle.css"

[[sites]]
  id = "sweets.github.io"
  url = "https://sweets.github.io/"
  css = "https://sweets.github.io/circular.css"
